// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qqcxzlqbujmqzqagpdoc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFxY3h6bHFidWptcXpxYWdwZG9jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA3NTM1MzAsImV4cCI6MjA1NjMyOTUzMH0.9sYqS-zip5hQ-S5tnoUGqEV3l50S0TSU1PiFwjXBbmk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);